#mysql,druid配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.194.158:3306/nanningapi?serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml

api:
  url: http://nncs-api.wsunw.com
  username: testapi
  password: abcd1234
  accesstokenurl: /api/nncs/auth/access_token/v1/get
  areadishonestyeventstatisurl: /api/nncs/score/areaDishonestyEventStatis/v1/batchSave
